import type { DensePreset, DenseSettings } from './types';

export const DEFAULT_DENSE_SETTINGS: DenseSettings = {
    disableAnimations: false,
    spacingBase: 8,
    typographyScale: 1,
    componentSize: 'medium',
    denseFormMargins: false,
    disableGlobalGutters: false,
    denseLists: false,
    listDisablePadding: false,
    toolbarDense: false,
    toolbarDisableGutters: false,
    tableSize: 'medium',
    compactButtonsAndChips: false,
    compactIconButtons: false,
    compactInputs: false,
    compactListsAndMenus: false,
    compactAccordionSummary: false,
    compactTableCells: false,
    compactTreeItems: false,
    dataGrid: {
        cellBlockPadding: '1px',
        density: 'standard',
    },
};

export const DENSE_PRESETS: Record<DensePreset, DenseSettings> = {
    default: DEFAULT_DENSE_SETTINGS,
    dense: {
        disableAnimations: true,
        spacingBase: 4,
        typographyScale: 1,
        componentSize: 'small',
        denseFormMargins: true,
        disableGlobalGutters: true,
        denseLists: true,
        listDisablePadding: true,
        toolbarDense: true,
        toolbarDisableGutters: true,
        tableSize: 'small',
        compactButtonsAndChips: true,
        compactIconButtons: true,
        compactInputs: true,
        compactListsAndMenus: true,
        compactAccordionSummary: true,
        compactTableCells: true,
        compactTreeItems: true,
        dataGrid: {
            cellBlockPadding: '1px',
            density: 'compact',
        },
    },
    densePlus: {
        disableAnimations: true,
        spacingBase: 2,
        typographyScale: 0.65,
        componentSize: 'small',
        denseFormMargins: true,
        disableGlobalGutters: true,
        denseLists: true,
        listDisablePadding: true,
        toolbarDense: true,
        toolbarDisableGutters: true,
        tableSize: 'small',
        compactButtonsAndChips: false,
        compactIconButtons: false,
        compactInputs: false,
        compactListsAndMenus: false,
        compactAccordionSummary: false,
        compactTableCells: false,
        compactTreeItems: false,
        dataGrid: {
            cellBlockPadding: '1px',
            density: 'compact',
        },
    },
};
